- name: Create new user to access master node in Big Data Latihan Lab
  hosts: all
  user: "{{ ansible_ssh_user }}"
  become: yes
  become_user: root
  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"