- name: Create new user to access master node in Big Data Latihan Lab
  hosts: all
  user: "{{ ansible_ssh_user }}"
  become: yes
  become_user: root
  
  tasks:
    - name: Add users | create users, shell, home dirs
      user: 
        name: "{{ item.username }}"
        shell: "/bin/bash createhome=yes"
        comment: "Created with Ansible"
        state: present
      with_items: "{{users}}"